# Generated by Django 5.1.3 on 2026-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0003_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
